### ISSUE TITLE
Index outside the bounds of the array

### ISSUE THREAD

**Issue by ericrot** [FieldCommGroup/WindowsHartIpClient#10]
Scenario: note had parsing enabled with Sample.hdf
1) Connect to gateway
    - Note there are adapters on the network with HART 5 devices attached.
2) "Send To All" command 9 with data 02030001
3) When the client sends command 9 to a HART 5 subdevice it returns RC64.
    a) the client logs the request and response messages
    b) then prints out "Index was outside the bounds of the array"

**Comment by wallyp** [comment]
should not try to parse a response when response code is an error.

**Comment by tjohnston-fcg** [comment]
We should not be parsing responses with an error response code.  From spec 307:

1-7, 16-23, 32-64, 9-13, 15, 28, 29, 65-95

**Comment by tjohnston-fcg** [comment]
Inhibited parsing for error responses.
