### ISSUE TITLE
Keep Alive

### ISSUE THREAD

**Issue by ericrot** [FieldCommGroup/WindowsHartIpClient#12]
The client should implement a keep alive thread that can be either enabled or disabled. The keep alive thread simply sends a keep alive message if there is currently no traffic on the IP connection (note publish messages count as traffic).

**Comment by tjohnston-fcg** [comment]
No keep alive messages were observed from the beta client.

**Comment by wallyp** [comment]
Spec states "The client must transmit this message periodically when no other communications ..."

**Comment by wallyp** [comment]
@ericrot why make it possible to enable/disable keep-alives?

**Comment by ericrot** [comment]
Certainly keepalives should be enabled by default. The only reason to allow the user to enable/disable the keepalives is maybe they don't want the connection to persist for an extended period. Or maybe it is just for testing/verification purposes.
One other point, keepalives should only be sent at a rate near the inactivity timeout set in the session init.

**Comment by tjohnston-fcg** [comment]
Spec says before 95% of the inactivity close time.  I have it hardwired for 90%.

**Comment by tjohnston-fcg** [comment]
I have keepalives at 8 minutes, session close time at 9 minutes.  The Inactivity Close Time is 10 minutes.  There is a new checkbox to enable keep alive messages that is enabled by default.
