### ISSUE TITLE
Use of Txx type in Sample.hdf

### ISSUE THREAD

**Issue by wallyp** [FieldCommGroup/WindowsHartIpClient#2]
T12 and T24 used in several commands (e.g., Commands 769, 793) does not seem correct.  HART Time types are 32bits.  All commands using Time type should be reviewed

**Comment by tjohnston-fcg** [comment]
T12 and T24 refer to 12- and 24-hour time formats.  In all cases 4 bytes are parsed to determine the time value.

As intended.
