### ISSUE TITLE
Cmd77 parsing

### ISSUE THREAD

**Issue by ericrot** [FieldCommGroup/WindowsHartIpClient#6]
When sending a command to a subdevice via command 77 it does not parse the embedded sub-device command which is what the user really wants.

**Comment by tjohnston-fcg** [comment]
When sending a command to a HART Mux, the responses are parsed properly.  But when sending a command to a subdevice, the HART data that is sent back is correct, but the parsing doesn't seem to be working and reads command 77 rather than the command sent to it.

**Comment by tjohnston-fcg** [comment]
Failure to unwrap the command 77 is repaired.
