### ISSUE TITLE
Cmd 77 parsing should show the Expanded device type not Mfg, Device type

### ISSUE THREAD

**Issue by ericrot** [FieldCommGroup/WindowsHartIpClient#7]
When parsing command 77, the Expanded Device type should be shown no the separate Mfg code and Device type.

Also, the MSBits of the Mfg code or Expanded device type code should not be set. The data in the command 77 request should come from the Cmd 0 information of the device which should not have those bits set.

**Comment by tjohnston-fcg** [comment]
With the repair of #6 we should no longer see a command 77 parsed, but rather its embedded command.  This issue should be resolved.
