### ISSUE TITLE
Unique Id in cmd 77

### ISSUE THREAD

**Issue by ericrot** [FieldCommGroup/WindowsHartIpClient#8]
The representation of the unique Id in command 77 is shown as individual hex bytes (0x3A0x210xA4). It should either be an integer or a 24 bit hex string (0x3A21A4). See command 0 parsing for an example

**Comment by tjohnston-fcg** [comment]
Repairing #6 means that we are no longer displaying a parsed command 77, but rather parsing the command embedded in command 77.  We should no longer see this issue.
