### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by ericrot** [FieldCommGroup/WindowsHartIpClient#9]
If you connect to a gateway/device and don't send any messages for a while, you get an unhandled exception. I assume it is because the gateway/device has closed the session based on the inactivity timeout but I am not sure (maybe it is something else).
Scenario:
1) Connect to gateway
2) Send several commands to subdevice(s)
3) Do some other work for several minutes
4) Send command 9 to gateway with variables 02030001
5) Unhandled exception occured.

**Comment by tjohnston-fcg** [comment]
This was caused by issue #4 and is functioning properly.
